server:
   port: 7001
spring:
   application:
      name: config-server
   cloud:
      config:
         server:
            git:
               uri: https://github.com/dengfan1/springcloud-config.git
               search-paths: configs-dir
               username: username
               password: password
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/